pipeline:
  flavour: mavenjava-11
build:
  push:
    mvn: |
     clean install -DskipTests=true
     dependency:copy-dependencies -DoutputDirectory=target/dependency
  tag:
    mvn: |
     versions:set -DnewVersion=$TAG
     clean install -DskipTests=true
     dependency:copy-dependencies -DoutputDirectory=target/dependency
unit_test:
  skip: true
  push:
    mvn: test
  tag:
    mvn: test
quality:
  skip: true
  sonarqube:
    skip: false
    properties: |
      sonar.sources=src/main/java
      sonar.junit.reportsPath=target/surefire-reports
      sonar.jacoco.reportPaths=target/coverage-reports/jacoco-unit.exec
      sonar.java.binaries=target/classes
      sonar.java.libraries=target/*.jar
#      sonar.cpd.exclusions=src/main/java/it/tim/mobileaps/apiunica/model/**
#      sonar.exclusions=src/main/java/it/tim/mobileaps/apiunica/model/**,src/main/java/it/tim/mobileaps/apiunica/controller/**
    active_gate: true
  check_style:
    skip: true
    source_code: ./src
    active_gate: false

security:
    skip: false
    srsca:
      skip: false
      configuration:
        scan:
          scan_path: "**/target/dependency/*"
          other_arguments: " --exclude **/target/dependency/activemq-all*.*"
    srsta:
      skip: false
      configuration:
        scan:
          scan_path: "./src/main/java"
          fp_security_file: "./falsi_positivi.csv"
        publisher:
          pattern: "src/main/java/securityreviewer-result.xml"
          fp_security_file: "./falsi_positivi.csv"


delivery:
  artifacts:
    skip: false
    tag:
      mvn: deploy -DaltReleaseDeploymentRepository=nexus::default::${NEXUS_LIB_URL}
      assets: $(mvn -s mvn-settings.xml -q exec:exec -Dexec.executable='echo' -Dexec.args=${NEXUS_LIB_URL}':${project.groupId}:${project.artifactId}:${project.version}')

  image:
    skip: false
    artifact:
      source: target/${SERVICE_NAME}-${TAG}.jar
      start: target/${SERVICE_NAME}-${TAG}.jar
  mailing_lists:
    - versions: alfa,beta
      mailto: marcello.villani@guest.telecomitalia.it
    - versions: release
      mailto: marcello.villani@guest.telecomitalia.it